### ISSUE TITLE
The size of tabs were changed

### ISSUE THREAD

**Issue by LIMUNADE** [Godiesc/AlpenBlue#2]
Basically they are small now. Any way to change that?

**Comment by Godiesc** [comment]
Tell me exactly the version of your firefox, its designed to firefox 89+ versions, 88 version still don't have Proton UI enabled.

**Comment by LIMUNADE** [comment]
Yes, it's exactly that. I'm using 88 version. Forgot to mention it in the description. 

Another problem of your theme is that it's [too dark in fav folders](https://cdn.discordapp.com/attachments/218029592382799874/842787551676071986/image.png). Is it because of the 88th version again?

**Comment by Godiesc** [comment]
I think so, you could test, in 88 version, adding this rules (https://www.reddit.com/r/firefox/comments/lmt8j4/megatoolbar_and_megamegabar_enable/)  in your about:config and see if its works fine, a small update to the contextual menu was added if you want to download again the chrome folder. :) but all the design was done to firefox with Proton UI.

**Comment by LIMUNADE** [comment]
Thanks for the quick fix. To be honest, I think small tabs are rather comfy. Need to get used to them. 

Keep up a good work! (‾◡◝)

**Comment by Godiesc** [comment]
well, the new Proton UI comes with a lot of extra size, my theme revert that with a small changes to solve that, in stable version of firefox dont work well, but in beta-nightly channels works fine. And you need to use the theme "Alpen Blue" that is in the description of the Github, maybe is your problem with dark labels in fav folders. :)

**Comment by LIMUNADE** [comment]
I've used your fix. It's all good now. You can close the issue. 

Everything is eye pleasing, vibrant and most importantly readable.

Take care! （￣︶￣）↗

**Comment by Godiesc** [comment]
Thanks, I appreciate you comments.
