### ISSUE TITLE
A AlpenPurple theme

### ISSUE THREAD

**Issue by alfredjophy** [Godiesc/AlpenBlue#3]
really love the alpenblue theme....would love to see a purple variant

Thanks : )

**Comment by Godiesc** [comment]
You mean something like this jeje its other of my themes: https://imgur.com/gallery/uSvr9HS , repository on git-hub: https://github.com/Godiesc/Chameleons-Beauty

**Comment by alfredjophy** [comment]
yeah , but it is not available on firefox addon page

**Comment by Godiesc** [comment]
The theme Alpenglow is one of firefox default themes, you can´t deleted of your firefox jeje. Edit: I just find out a theme for you: https://addons.mozilla.org/es/firefox/addon/alpenglow-dark/

**Comment by alfredjophy** [comment]
i tried alpenglow dark but it doesnt feel good like AlpenBlue...could you make your chameleon theme in addons.mozilla.org

**Comment by alfredjophy** [comment]
i tried alpenglow dark but it doesnt feel good like AlpenBlue...could you make your chameleon theme in addons.mozilla.org

**Comment by Godiesc** [comment]
Make another theme isnt a part of "issues" to fix, sorry, but make another theme and keep it updated is hard to do, so maybe you could change the color yourself in the rules of userChrome.css and make it perfect to you.
