### ISSUE TITLE
Unmute button switches place and isn't keeping style.

### ISSUE THREAD

**Issue by KawsyFurry** [Godiesc/AlpenBlue#4]
The unmute button doesn't keep the design and switches over to the top side. It's not to do with the play/pause extension but still does it without it.

![image](https://user-images.githubusercontent.com/88117876/173852988-2fb1fe78-073c-4312-9b9c-9b5304720156.png)

I am on Firefox Nightly 103.0a1 on a 64 bit windows 10 pro device.

**Comment by Godiesc** [comment]
hi, it was designed that way intentionally. You think its a good idea keep the label on muted tabs? you think it is necessary?

**Comment by KawsyFurry** [comment]
Guess it's a personal opinion then. Personally the design would look a lot more seamless and intuitive if the design was kept all throughout. It's up to you in the end, I just felt like it was an unexpected behavior initially. Thank you for clarifying.
