### ISSUE TITLE
[Feature Request] One Line version & Main-Image

### ISSUE THREAD

**Issue by ghost** [Godiesc/AlpenBlue#5]
Thank you so much for making this theme. I love using it with Nightly. I was wondering if you would make an one liner version of this and add the main-image feature from your opera-gx theme. Totally fine if you decline.

Thanks again.

**Comment by Godiesc** [comment]
hi, I'll try to do that, isn't a complicated thing the oneline config, the main-image I don't know if could be hard but the gradient line in selected tab isn't compatible with themes with images, I think it is not possible to do.

**Comment by ghost** [comment]
Hey I saw you added the one line config, that was so fast. Thank you so much. This is my favourite css theme now.

**Comment by Godiesc** [comment]
I changed a lot of little things into the theme files to make the oneline config, maybe you will need to download again the theme, maybe. 💙

**Comment by ghost** [comment]
Yes, I've redownloaded all the files. You're the best. Cheers!
